version: "3.2"

volumes:
  data-hub-postgres:
  kafka:

services:
  db:
    container_name: data_hub_postgres_container
    image: postgres:11.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
    volumes:
      - type: volume
        source: data-hub-postgres
        target: /var/lib/postgresql/data
